MODULES = [
    "Dashboard",
    "Franchise Settings",
    "Franchise Details",
    "Franchise Agreement",
    "Royalty Scale",
    "Performance",
    "Heat Map",
    "Manuals",
    "Royalties",
    "Monthly Figures",
    "Joinings",
    "Funeral Services",
    "Insurance Claims",
    "Attendance",
    "Finance",
    "Users",
    "Franchise Employees",
    "User Roles",
    "Franchise Management",
    "Imports & Data",
    "Audit Logs",
    "System Administration",
    "PDF Templates",
    "Email Templates",
    "Backup Management",
]

ACTIONS = ["view", "add", "edit", "delete", "export", "approve", "import", "manage"]

ROLE_TEMPLATES = {
    "Admin": "Full unrestricted system access.",
    "Regional Manager": "Can view and manage assigned franchise performance and reports.",
    "Finance Manager": "Can manage finance, royalties, monthly figures, and approvals.",
    "Finance Assistant": "Can capture and update finance-related operational records.",
    "Franchise Manager": "Can manage own franchise records and exports, excluding admin settings.",
    "Franchise User": "Can view and capture normal franchise operational records and manage own franchise employee users.",
    "Franchise Employee": "Employee created by a franchise user and limited to that franchise data.",
    "Read Only User": "Can view allowed pages and reports only.",
}

ROLE_DEFAULTS = {
    "Admin": "ALL",
    "Regional Manager": {
        # Regional Managers see only franchises linked to their user account.
        # They do not receive Franchise Management view/manage because that would expose all franchises.
        "Dashboard": ["view"],
        "Franchise Settings": ["view"],
        "Franchise Details": ["view", "edit", "export"],
        "Franchise Agreement": ["view"],
        "Royalty Scale": ["view"],
        "Performance": ["view", "export"],
        "Royalties": ["view", "export"],
        "Monthly Figures": ["view", "export"],
        "Heat Map": ["view", "export"],
        "Manuals": ["view"],
    },
    "Finance Manager": {
        "Dashboard": ["view"],
        "Franchise Settings": ["view"],
        "Franchise Details": ["view", "edit", "export"],
        "Franchise Agreement": ["view", "edit", "manage"],
        "Royalty Scale": ["view", "edit", "manage"],
        "Franchise Management": ["view", "manage"],
        "Performance": ["view", "export", "manage"],
        "Royalties": ["view", "add", "edit", "export", "approve"],
        "Monthly Figures": ["view", "edit", "delete", "export", "approve", "import"],
        "Finance": ["view", "add", "edit", "export", "approve"],
        "Insurance Claims": ["view", "edit", "export", "approve"],
    },
    "Finance Assistant": {
        "Dashboard": ["view"],
        "Franchise Management": ["view", "manage"],
        "Users": ["view", "edit"],
        "Performance": ["view", "export"],
        "Insurance Claims": ["view", "add", "edit", "export"],
        "Royalties": ["view", "add", "edit", "export"],
        "Monthly Figures": ["view", "import", "edit", "export"],
        "Finance": ["view", "add", "edit", "export"],
    },
    "Franchise Manager": {
        "Dashboard": ["view"],
        "Franchise Settings": ["view"],
        "Franchise Details": ["view", "edit", "export"],
        "Franchise Agreement": ["view"],
        "Royalty Scale": ["view"],
        "Performance": ["view", "export"],
        "Royalties": ["view", "export"],
        "Monthly Figures": ["view", "export"],
        "Heat Map": ["view"],
        "Manuals": ["view"],
        "Franchise Employees": ["view", "add", "edit", "delete", "manage"],
    },
    "Franchise User": {
        "Dashboard": ["view"],
        "Franchise Settings": ["view"],
        "Franchise Details": ["view", "edit", "export"],
        "Franchise Agreement": ["view"],
        "Royalty Scale": ["view"],
        "Performance": ["view", "export"],
        "Royalties": ["view", "export"],
        "Monthly Figures": ["view", "export"],
        "Heat Map": ["view"],
        "Manuals": ["view"],
        "Franchise Employees": ["view", "add", "edit", "delete", "manage"],
    },
    "Franchise Employee": {
        "Dashboard": ["view"],
        "Franchise Settings": ["view"],
        "Franchise Details": ["view", "export"],
        "Franchise Agreement": ["view"],
        "Royalty Scale": ["view"],
        "Performance": ["view"],
        "Royalties": ["view"],
        "Monthly Figures": ["view"],
        "Heat Map": ["view"],
        "Manuals": ["view"],
    },
    "Read Only User": {
        "Dashboard": ["view"],
        "Franchise Settings": ["view"],
        "Franchise Details": ["view", "export"],
        "Franchise Agreement": ["view"],
        "Royalty Scale": ["view"],
        "Performance": ["view"],
        "Heat Map": ["view"],
        "Manuals": ["view"],
        "Royalties": ["view"],
        "Monthly Figures": ["view"],
    },
}

def permission_code(module, action):
    return f"{module.lower().replace(' & ', '_').replace(' ', '_')}:{action}"
