"""Update monthly figures and user protection

Revision ID: 002284c1c768
Revises: 77c0044fe12d
Create Date: 2026-06-11 14:53:39.869223

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '002284c1c768'
down_revision = '77c0044fe12d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('monthly_figures', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gross_turnover', sa.Numeric(precision=12, scale=2), nullable=False))
        batch_op.add_column(sa.Column('cash', sa.Numeric(precision=12, scale=2), nullable=False))
        batch_op.add_column(sa.Column('funeral_receipts', sa.Numeric(precision=12, scale=2), nullable=False))
        batch_op.add_column(sa.Column('claim_receipts', sa.Numeric(precision=12, scale=2), nullable=False))
        batch_op.add_column(sa.Column('society_receipts', sa.Numeric(precision=12, scale=2), nullable=False))
        batch_op.add_column(sa.Column('cash_sales', sa.Numeric(precision=12, scale=2), nullable=False))
        batch_op.add_column(sa.Column('tombstone_receipts', sa.Numeric(precision=12, scale=2), nullable=False))
        batch_op.add_column(sa.Column('obo_service_receipts', sa.Numeric(precision=12, scale=2), nullable=False))
        batch_op.add_column(sa.Column('sales', sa.Numeric(precision=12, scale=2), nullable=False))
        batch_op.add_column(sa.Column('insurance_receipts', sa.Numeric(precision=12, scale=2), nullable=False))
        batch_op.add_column(sa.Column('insurance_payover', sa.Numeric(precision=12, scale=2), nullable=False))
        batch_op.add_column(sa.Column('admin_fee', sa.Numeric(precision=12, scale=2), nullable=False))
        batch_op.add_column(sa.Column('insurance_joinings', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('mf_files', sa.Integer(), nullable=False))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_login_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('deactivated_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('deactivation_reason', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('deactivation_reason')
        batch_op.drop_column('deactivated_at')
        batch_op.drop_column('last_login_at')

    with op.batch_alter_table('monthly_figures', schema=None) as batch_op:
        batch_op.drop_column('mf_files')
        batch_op.drop_column('insurance_joinings')
        batch_op.drop_column('admin_fee')
        batch_op.drop_column('insurance_payover')
        batch_op.drop_column('insurance_receipts')
        batch_op.drop_column('sales')
        batch_op.drop_column('obo_service_receipts')
        batch_op.drop_column('tombstone_receipts')
        batch_op.drop_column('cash_sales')
        batch_op.drop_column('society_receipts')
        batch_op.drop_column('claim_receipts')
        batch_op.drop_column('funeral_receipts')
        batch_op.drop_column('cash')
        batch_op.drop_column('gross_turnover')

    # ### end Alembic commands ###
