"""Add royalty gross method

Revision ID: 402d5d8f4037
Revises: 16e8f5aef664
Create Date: 2026-06-11 19:25:02.894182

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '402d5d8f4037'
down_revision = '16e8f5aef664'
branch_labels = None
depends_on = None


def upgrade():
    op.add_column(
        'franchises',
        sa.Column(
            'royalty_gross_method',
            sa.String(length=20),
            nullable=True
        )
    )

    op.execute(
        "UPDATE franchises "
        "SET royalty_gross_method='new' "
        "WHERE royalty_gross_method IS NULL"
    )

    op.alter_column(
        'franchises',
        'royalty_gross_method',
        nullable=False
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('franchises', schema=None) as batch_op:
        batch_op.drop_column('royalty_gross_method')

    # ### end Alembic commands ###
