"""Add monthly figures and standard logo

Revision ID: 77c0044fe12d
Revises: 5c5e979c454f
Create Date: 2026-06-11 10:13:04.108527

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '77c0044fe12d'
down_revision = '5c5e979c454f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('monthly_figures',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('franchise_id', sa.Integer(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('cash_received', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('insurance_received', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('payover', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('other_income', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('number_of_funerals', sa.Integer(), nullable=False),
    sa.Column('number_of_policies', sa.Integer(), nullable=False),
    sa.Column('number_of_claims', sa.Integer(), nullable=False),
    sa.Column('gross_revenue', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('royalty_percentage', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('royalty_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('minimum_royalty_applied', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('locked_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['franchise_id'], ['franchises.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('monthly_figures', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_monthly_figures_franchise_id'), ['franchise_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_monthly_figures_month'), ['month'], unique=False)
        batch_op.create_index(batch_op.f('ix_monthly_figures_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_monthly_figures_year'), ['year'], unique=False)

    with op.batch_alter_table('franchises', schema=None) as batch_op:
        batch_op.drop_column('logo_url')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('franchises', schema=None) as batch_op:
        batch_op.add_column(sa.Column('logo_url', sa.VARCHAR(length=500), autoincrement=False, nullable=True))

    with op.batch_alter_table('monthly_figures', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_monthly_figures_year'))
        batch_op.drop_index(batch_op.f('ix_monthly_figures_status'))
        batch_op.drop_index(batch_op.f('ix_monthly_figures_month'))
        batch_op.drop_index(batch_op.f('ix_monthly_figures_franchise_id'))

    op.drop_table('monthly_figures')
    # ### end Alembic commands ###
